#!/usr/bin/env python

import obspy
import seispy
import sys
import numpy as np
import h5py
from matplotlib import pyplot as plt
import glob
from scipy.interpolate import interp1d
import matplotlib.gridspec as gridspec
from scipy.signal import tukey


dir_list = glob.glob('*')
env_list = []
h5name = sys.argv[1]

range_list = []
stcoord = []
evcoord = []
stdlist = [[] for ii in range(0,21)]
stdarray = np.zeros((21,10000))

for dir in dir_list:
    if '5.5' not in dir:
        try:
            f = h5py.File(dir+'/Processed/'+h5name,'r')
            for ii in range(0,21):
                range_str = str(ii/2.+130)
                for jj in range(0,2000):
                    randi = np.random.randint(0,f[range_str+'_deg'].shape[0])
                    rand_env = f[range_str+'_deg'][randi]
                    stdlist[ii].append(np.nan_to_num(rand_env/rand_env.max()))
            f.close()
        except IOError:
            continue

for idx,ii in enumerate(stdlist):
    stdarray[idx] = np.std(ii,axis=0)
#for idx,ii in enumerate(stdlist):
#    stdarray[idx] += np.std(np.vstack([jj for jj in ii]),axis=0)

