#!/usr/bin/env python

import obspy
import seispy
import sys
import numpy as np
import h5py
from matplotlib import pyplot as plt
import glob
from scipy.interpolate import interp1d
import random
from scipy.signal import tukey

# Combine synthetic envelopes for PKP precursors

dir_list = [sys.argv[1],
       sys.argv[2],
       sys.argv[3],
       sys.argv[4]]

env_name = sys.argv[5]
#h5title = 'EED_{}_{}_{}_{}_{}_{}'.format(
#        dir_list[0].split('_')[-2],
#        dir_list[0].split('_')[-1],
#        dir_list[1].split('_')[-1],
#        dir_list[2].split('_')[-1],
#        dir_list[3].split('_')[-1],
#        env_name)
h5title = sys.argv[6]+'.h5'

file_1 = h5py.File(dir_list[0]+'/'+env_name,'r')
file_2 = h5py.File(dir_list[1]+'/'+env_name,'r')
file_3 = h5py.File(dir_list[2]+'/'+env_name,'r')
file_4 = h5py.File(dir_list[3]+'/'+env_name,'r')

env_list = [file_1['env'][...],
            file_2['env'][...],
            file_3['env'][...],
            file_4['env'][...]]

file_1.close()
file_2.close()
file_3.close()
file_4.close()

mean_list = []
seconds =  int(env_list[0].shape[1]/40*2.5)
for ii in range(0,4000):
    ind = [random.randint(0,3) for ii in range(0,4)]
    rand_roll = [int(np.random.normal(0,seconds)) for ii in range(0,4)]
    random_list = [np.roll(env_list[ii],rand_roll[ii]) for ii in ind]
    mean = np.mean(np.array(random_list),axis=0)
    mean_list.append(mean)
random_range = np.zeros(mean_list[0].shape)
for ii in range(10000):
    el = random.randint(0,len(mean_list)-1)
    ind = random.randint(0,mean_list[0].shape[0]-1)
    random_range[ind] += mean_list[el][ind]

std_list = np.std(np.array(mean_list),axis=0)
mean_list = np.mean(np.array(mean_list),axis=0)
mean_list = mean_list/mean_list.max(axis=1)[:,None]


mean_list *= tukey(mean_list.shape[1],alpha=0.3)
f = h5py.File(h5title,'w')
f.create_dataset('env',data=mean_list)
f.create_dataset('std',data=std_list)
f.close()

