#!/home/samhaug/anaconda2/bin/python
import numpy as np
from matplotlib import pyplot as plt

morb_0 = np.genfromtxt('EED_000/MORB.dat')
morb_0 *= 1./morb_0.max()
tc_0 = np.genfromtxt('EED_000/TandC.dat')
tc_0[:,0:2] *= 1./tc_0[:,0].max()

morb_7 = np.genfromtxt('EED_007/MORB.dat')
morb_7 *= 1./morb_7.max()
tc_7 = np.genfromtxt('EED_007/TandC.dat')
tc_7[:,0:2] *= 1./tc_7[:,0].max()

fig, ax = plt.subplots(figsize=(5,5),facecolor='white')
ax = plt.axes(frameon=False)
ax.set_xticks([])
ax.set_yticks([])
ax.xaxis.set_visible(False)
ax.yaxis.set_visible(False)

x_off = 2.2
y_off = 2.2
ax.scatter(morb_0[::3,0],morb_0[::3,1],lw=0,s=0.2,c='k',alpha=0.7)
im1 = ax.scatter(x_off+tc_0[::1,0],tc_0[::1,1],c=tc_0[::1,2]+5,
                 lw=0,s=0.5,cmap='seismic')

ax.scatter(morb_7[::3,0],morb_7[::3,1]-y_off,lw=0,s=0.2,c='k',alpha=0.7)
im2 = ax.scatter(x_off+tc_7[::1,0],tc_7[::1,1]-y_off,c=tc_7[::1,2]+5,
                 lw=0,s=0.5,cmap='seismic')


cbar1 = fig.add_axes([0.425,0.49,0.155,0.03])
cbar1.set_yticks([])
cbar1.xaxis.label.set_size(10)
cbar1.tick_params(axis='both', which='major', labelsize=7)
plt.colorbar(im1,cax=cbar1,orientation='horizontal',ticks=[])
#plt.colorbar(im1,cax=cbar1,orientation='horizontal',
#             ticks=[270,tc_0[::5,2].max()+5])
#cbar2 = fig.add_axes([0.642,0.268,0.155,0.03])
#plt.colorbar(im2,cax=cbar2,orientation='horizontal',
#             ticks=[270,tc_7[::5,2].max()+5])
#plt.colorbar(im2,cax=cbar2,orientation='horizontal',ticks=[])
#cbar2.xaxis.label.set_size(10)
#cbar2.tick_params(axis='both', which='major', labelsize=7)
#cbar2.set_yticks([])
#ax.text(2.09,-0.15,'T(K)',size=10)
#ax.text(2.09,-2.25,'T(K)',size=10)
plt.tight_layout()
plt.show()


