#!/usr/bin/env python

import numpy as np
import glob
import sys
import os
import subprocess
import shutil


def main():
    sac_list = glob.glob('./seismograms/*/*/*')
    pz_list = glob.glob('./polezero/*/*')

    os.mkdir('./Processed')

    for sac in sac_list:
        sac_year = sac.split('_')[1]
        sac_key = sac.split('/')[-1][0:-4]
        year_track = []
        pz_track = []
        for pz in pz_list:
            pz_year = pz.split('_')[0][-4::]
            pz_key = pz[0:-24].split('/')[-1]
            if pz_key == sac_key and float(sac_year) >= float(pz_year):
                out_file = './Processed/'+sac.split('/')[2]+'_'+sac.split('/')[-1]
                year_track.append(pz_year)
                pz_track.append(pz)
        if len(year_track) != 0:
            ind = year_track.index(max(year_track))
            sac_rr(sac,pz_track[ind],out_file)
        elif len(year_track) == 0:
            subprocess.call('cp {} ./Processed/'.format(sac),shell=True)

def sac_rr(sac_file,pz_file,out_sac):

    p = subprocess.Popen(['sac'],
                     stdout = subprocess.PIPE,
                     stdin  = subprocess.PIPE,
                     stderr = subprocess.STDOUT)
    s = "echo on\n"
    s += '''
         setbb pzfile {}
         read {}
         rtr
         taper
         trans from polezero S %pzfile to none freq 0.050 0.1 20 40
         mul 1.0e9
         write {}.filtered
         '''.format(pz_file,sac_file,out_sac)
    s += "quit\n"

    out = p.communicate(s)
    print out[0]

if os.path.exists('./Processed/'):
    shutil.rmtree('./Processed/')

main()


